name: Build Upsync Windows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Publish Upsync
        run: |
          dotnet publish -p:PublishSingleFile=true --self-contained -c Release src/tools/upsync/upsync.csproj
          

      - name: Create ZIP of the artifact (Windows)
        run: |
          powershell Compress-Archive -Path out/upsync/Release/net9.0/win-x64/publish/* -DestinationPath out/upsync-windows.zip

      - name: Upload artifact to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: windows-${{ github.sha }}
          files: out/upsync-windows.zip
          